### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Syxxxx**
Add Dbus service file

### CODE REVIEW

**Comment by zygous** [comment]
Ah, yes, thanks for this; I'd forgotten this file.

The Exec line should include the flag --gapplication-service, could you please add that and then squash your commits; then I'll merge your patch.

**Comment by Syxxxx** [comment]
:), thanks for your useful app !
i have add the flag (can you check is it ok for you)

**Comment by zygous** [comment]
Yep, that's great. Could you squash those commits into one though please?

I'm glad you find it useful ☺

**Comment by Syxxxx** [comment]
you can't merge patch-1 automatically ? patch-1 have the 3 commits. if i don't well understand your query, please explain how i can squash those commits.

I thinks you have to add some information to edit ssh_config for deactivate the host hash in your Readme.

It's not useful it is vital for me: D many thanks !

**Comment by zygous** [comment]
Yep, I'd prefer for the patch to only comprise one commit. See here for
example:
https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit
.

Good call regarding HashKnownHosts. That depends upon your distro (they're
not hashed by default on Fedora for example), but useful to note.

On 20 May 2015 at 13:05, Syxxxx notifications@github.com wrote:

> you can't merge patch-1 automatically ? patch-1 have the 3 commits. if i
> don't well understand your query, please explain how i can squash those
> commits.
> 
> I thinks you have to add some information to edit ssh_config for
> deactivate the host hash in your Readme.
> 
> It's not useful it is vital for me: D many thanks !
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zygous/ssh-search-provider/pull/1#issuecomment-103859329
> .

## 

"Racing turtles, the grapefruit is winning..."

**Comment by Syxxxx** [comment]
Finally done ... (my first rebase youhou !!!)

**Comment by zygous** [comment]
Great, thanks very much!

**Pull request merged**
